apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: kansberrypipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kansberrypipelinesjavascriptdocker 
    spec:
      containers:
        - name: kansberrypipelinesjavascriptdocker 
          image: cincomeastus2devkuberegistry.azurecr.io/kansberrypipelinesjavascriptdocker
          ports:
          - containerPort: 8080